### ISSUE TITLE
java: 无法访问me.zhangjh.chatgpt.client.ChatGptService   错误的类文件: /C:/Users/jianjianjianjian/.m2/repository/me/zhangjh/chatgpt-starter/2.0.3/chatgpt-starter-2.0.3.jar!/me/zhangjh/chatgpt/client/ChatGptService.class     类文件具有错误的版本 55.0, 应为 52.0     请删除该文件或确保该文件位于正确的类路径子目录中。

### ISSUE THREAD

**Issue by 1500256797** [zhangjh/chatgpt-starter#3]
java: 无法访问me.zhangjh.chatgpt.client.ChatGptService
  错误的类文件: /C:/Users/jianjianjianjian/.m2/repository/me/zhangjh/chatgpt-starter/2.0.3/chatgpt-starter-2.0.3.jar!/me/zhangjh/chatgpt/client/ChatGptService.class
    类文件具有错误的版本 55.0, 应为 52.0
    请删除该文件或确保该文件位于正确的类路径子目录中。

**Comment by zhangjh** [comment]
请检查你依赖的SpringBoot版本，确保是2.x版本

**Comment by zhangjh** [comment]
工程依赖的jdk版本是jdk11，请一并检查

**Comment by zhangjh** [comment]
![image](https://user-images.githubusercontent.com/3371714/226946587-b9cc9121-0e19-48a2-a18c-3b09eb8896a8.png)
另外这些基础的工程性问题希望能够先自行搜索解决，issue主要为了解决项目自身的缺陷和bug，谢谢
